/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-23 08:40:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.festival;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class festival_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ezentour/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/festival/../include/header.jsp", Long.valueOf(1563813072000L));
    _jspx_dependants.put("/WEB-INF/views/festival/../include/menu.jsp", Long.valueOf(1563813072000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1559550078729L));
    _jspx_dependants.put("jar:file:/D:/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ezentour/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Favicon -->\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/favicon3.png\">\n");
      out.write("<!-- Stylesheet -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/style.css\">\n");
      out.write("<!-- Font -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("<!--\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.rawgit.com/innks/NanumSquareRound/master/nanumsquareround.min.css\">\n");
      out.write("-->\n");
      out.write("\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\tbody\t\t{ font-family: 'Nanum Gothic', sans-serif; }\n");
      out.write("\t.normal\t\t{ font-weight: 400 }\n");
      out.write("\t.bold\t\t{ font-weight: 700 }\n");
      out.write("\t.bolder\t\t{ font-weight: 800 }\n");
      out.write("\t.light\t\t{ font-weight: 300 }\n");
      out.write("\t.h1-title   { font-family: 'Nanum Gothic', sans-serif; color: white; }\n");
      out.write("\t.h1-title-main   { font-family: 'Nanum Gothic', sans-serif; color: white; font-size: 60px; }\n");
      out.write("\t.breadcrumb-content .breadcrumb .breadcrumb-item + .breadcrumb-item::before {\n");
      out.write("     font-family: \"FontAwesome\";\n");
      out.write("     font-weight: 900;\n");
      out.write("     content: '\\f105';\n");
      out.write("     color: #ffffff; }\n");
      out.write("</style>");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title>EzenTour</title>\n");
      out.write("<style>\n");
      out.write("table {\n");
      out.write("\ttext-align: center\n");
      out.write("}\n");
      out.write("\n");
      out.write("td {\n");
      out.write("\tvalign: middle\n");
      out.write("}\n");
      out.write("\n");
      out.write(".roberto-btn1 {\n");
      out.write("\tposition: relative;\n");
      out.write("\tmin-width: 60px;\n");
      out.write("\theight: 38px;\n");
      out.write("\tline-height: 46px;\n");
      out.write("\tfont-size: 16px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\ttext-transform: capitalize;\n");
      out.write("\tbackground-color: #1cc3b2;\n");
      out.write("\tcolor: #ffffff;\n");
      out.write("\tborder: none;\n");
      out.write("\tborder-radius: 2px;\n");
      out.write("\t-webkit-transition-duration: 500ms;\n");
      out.write("\t-o-transition-duration: 500ms;\n");
      out.write("\ttransition-duration: 500ms;\n");
      out.write("\tmargin-left: 10px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Preloader -->\n");
      out.write("<div id=\"preloader\">\n");
      out.write("\t<div class=\"loader\"></div>\n");
      out.write("</div>\n");
      out.write("<!-- /Preloader -->\n");
      out.write("\n");
      out.write("<!-- Header Area Start -->\n");
      out.write("<header class=\"header-area\">\n");
      out.write("\t<!-- Search Form -->\n");
      out.write("\t<div class=\"search-form d-flex align-items-center\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<form action=\"index.html\" method=\"get\">\n");
      out.write("\t\t\t\t<input type=\"search\" name=\"search-form-input\" id=\"searchFormInput\"\n");
      out.write("\t\t\t\t\tplaceholder=\"Type your keyword ...\">\n");
      out.write("\t\t\t\t<button type=\"submit\">\n");
      out.write("\t\t\t\t\t<i class=\"icon_search\"></i>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Main Header Start -->\n");
      out.write("\t<div class=\"main-header-area\">\n");
      out.write("\t\t<div class=\"classy-nav-container breakpoint-off\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<!-- Classy Menu -->\n");
      out.write("\t\t\t\t<nav class=\"classy-navbar justify-content-between\" id=\"robertoNav\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t<a class=\"nav-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/ezenlogo.png\" alt=\"\"></a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Navbar Toggler -->\n");
      out.write("\t\t\t\t\t<div class=\"classy-navbar-toggler\">\n");
      out.write("\t\t\t\t\t\t<span class=\"navbarToggler\"><span></span></span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Menu -->\n");
      out.write("\t\t\t\t\t<div class=\"classy-menu\">\n");
      out.write("\t\t\t\t\t\t<!-- Menu Close Button -->\n");
      out.write("\t\t\t\t\t\t<div class=\"classycloseIcon\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cross-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"top\"></span><span class=\"bottom\"></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- Nav Start -->\n");
      out.write("\t\t\t\t\t\t<div class=\"classynav\">\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"nav\" style=\"font-weight : bold\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/festival/main\">축제</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tour/main\">관광</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hotel/main\">숙소</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/main?page=1&search= \">자유게시판</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 접속 계정에 따라 메뉴바 다르게 보이기 -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 관리자 메뉴바 -->\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-left : 120px; \">\t\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Nav End -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</header>\n");
      out.write("<!-- Header Area End -->");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Breadcrumb Area Start -->\n");
      out.write("\t<div\n");
      out.write("\t\tclass=\"breadcrumb-area contact-breadcrumb bg-img bg-overlay jarallax\"\n");
      out.write("\t\tstyle=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/festival.jpeg);\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"breadcrumb-content text-center mt-100\">\n");
      out.write("\t\t\t\t\t\t<h1 class=\"h1-title\">축제 정보</h1>\n");
      out.write("\t\t\t\t\t\t<nav aria-label=\"breadcrumb\">\n");
      out.write("\t\t\t\t\t\t\t<ol class=\"breadcrumb justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"breadcrumb-item active\" aria-current=\"page\">Festival</li>\n");
      out.write("\t\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Breadcrumb Area End -->\n");
      out.write("\n");
      out.write("\t<!-- Google Maps & Contact Info Area Start -->\n");
      out.write("\t<section class=\"google-maps-contact-info\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"google-maps-contact-content\">\n");
      out.write("\t\t\t\t<div class=\"row center-content-between align-items-end\">\n");
      out.write("\t\t\t\t\t<div class=\"col-4 col-md-2 col-lg-2\">\n");
      out.write("\t\t\t\t\t\t<label for=\"f_start\">축제 기간</label> <input type=\"date\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"f_start\" name=\"f_start\" value=\"2019-07-01\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-4 col-md-2 col-lg-2\">\n");
      out.write("\t\t\t\t\t\t<label for=\"f_end\"></label> <input type=\"date\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"f_end\" name=\"f_end\" value=\"2019-12-31\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t <button type=\"submit\" class=\"roberto-btn1\" id=\"btnd\">검색</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<!-- Google Maps -->\n");
      out.write("\t\t\t\t<div class=\"google-maps\">\n");
      out.write("\t\t\t\t\t<div id=\"map\" style=\"width: 100%; height: 500px; boarder: 1px solid black;\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<script type=\"text/javascript\"\n");
      out.write("\t\t\t\t\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=f3214d52dc541ad022a4463064eeff3c&libraries=services,clusterer,drawing\"></script>\n");
      out.write("\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div  \n");
      out.write("\t\t\t\t\tmapOption = {\n");
      out.write("\t\t\t\t\t\tcenter : new kakao.maps.LatLng(36.36181333069756,\n");
      out.write("\t\t\t\t\t\t\t\t127.37896281500157), // 지도의 중심좌표\n");
      out.write("\t\t\t\t\t\tlevel : 7\n");
      out.write("\t\t\t\t\t// 지도의 확대 레벨\n");
      out.write("\t\t\t\t\t};\n");
      out.write("\t\t\t\t\tvar map = new kakao.maps.Map(mapContainer, mapOption);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\t // 지도를 생성합니다\n");
      out.write("\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/festival/PublicData.do',\n");
      out.write("\t\t\t\t\t\ttype : 'get',\n");
      out.write("\t\t\t\t\t\tdata: { start : document.getElementById(\"f_start\").value,\n");
      out.write("\t\t\t\t\t\t\t\tend : document.getElementById(\"f_end\").value},\n");
      out.write("\t\t\t\t\t\tdataType : 'json',\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t\t\t\tconsole.log(data.response.body.items.item);\n");
      out.write("\t\t\t\t\t\t\tvar positions = data.response.body.items.item;\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\tfor (var i = 0; i < positions.length; i++) {\n");
      out.write("\t\t\t\t\t\t\t\tvar output = new Object();\n");
      out.write("\t\t\t\t\t\t\t\toutput.title = positions[i].title;\n");
      out.write("\t\t\t\t\t\t\t\toutput.addr = positions[i].addr1;\n");
      out.write("\t\t\t\t\t\t\t\toutput.tel = positions[i].tel;\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\toutput.date = positions[i].eventstartdate + \" ~ \" + positions[i].eventenddate;\n");
      out.write("\t\t\t\t\t\t\t\toutput.img = positions[i].firstimage2;\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t// 마커를 생성합니다\n");
      out.write("\t\t\t\t\t\t\t\tvar marker = new kakao.maps.Marker({\n");
      out.write("\t\t\t\t\t\t\t\t\tmap : map, // 마커를 표시할 지도\n");
      out.write("\t\t\t\t\t\t\t\t\tposition : new kakao.maps.LatLng(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpositions[i].mapy,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpositions[i].mapx)\n");
      out.write("\t\t\t\t\t\t\t\t// 마커의 위치\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t// 마커에 표시할 인포윈도우를 생성합니다 \n");
      out.write("\t\t\t\t\t\t\t\tvar infowindow = new kakao.maps.InfoWindow({\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent : \"<b>\" + positions[i].title\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ \"</b><br>\" + positions[i].addr1,\n");
      out.write("\t\t\t\t\t\t\t\t\tremovable : true\n");
      out.write("\t\t\t\t\t\t\t\t// 인포윈도우에 표시할 내용\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t// 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다\n");
      out.write("\t\t\t\t\t\t\t\t// 이벤트 리스너로는 클로저를 만들어 등록합니다 \n");
      out.write("\t\t\t\t\t\t\t\t// for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다\n");
      out.write("\t\t\t\t\t\t\t\tkakao.maps.event.addListener(marker, 'click',\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmakeOverListener(map, marker,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tinfowindow, output));\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t// 인포윈도우를 표시하는 클로저를 만드는 함수입니다 \n");
      out.write("\t\t\t\t\tfunction makeOverListener(map, marker, infowindow, output) {\n");
      out.write("\t\t\t\t\t\treturn function() {\n");
      out.write("\t\t\t\t\t\t\tinfowindow.open(map, marker);\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"title\").innerHTML = output.title;\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"date\").innerHTML = output.date;\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"addr\").innerHTML = output.addr;\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"tel\").innerHTML = output.tel;\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"img\").innerHTML = \"<img src='\" + output.img + \"'>\";\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t// 인포윈도우를 닫는 클로저를 만드는 함수입니다 \n");
      out.write("\t\t\t\t\tfunction makeOutListener(infowindow) {\n");
      out.write("\t\t\t\t\t\treturn function() {\n");
      out.write("\t\t\t\t\t\t\tinfowindow.close();\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$(\"#btnd\").click(function(){  \n");
      out.write("\t\t\t\t\t\tvar map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/festival/PublicData.do',\n");
      out.write("\t\t\t\t\t\t\ttype : 'get',\n");
      out.write("\t\t\t\t\t\t\tdata: { start : document.getElementById(\"f_start\").value,\n");
      out.write("\t\t\t\t\t\t\t\t\tend : document.getElementById(\"f_end\").value},\n");
      out.write("\t\t\t\t\t\t\tdataType : 'json',\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(data.response.body.items.item);\n");
      out.write("\t\t\t\t\t\t\t\tvar positions = data.response.body.items.item;\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\tfor (var i = 0; i < positions.length; i++) {\n");
      out.write("\t\t\t\t\t\t\t\t\tvar output = new Object();\n");
      out.write("\t\t\t\t\t\t\t\t\toutput.title = positions[i].title;\n");
      out.write("\t\t\t\t\t\t\t\t\toutput.addr = positions[i].addr1;\n");
      out.write("\t\t\t\t\t\t\t\t\toutput.tel = positions[i].tel;\n");
      out.write("\t\t\t\t\t\t\t\t\toutput.date = positions[i].eventstartdate\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ \" ~ \" + positions[i].eventenddate;\n");
      out.write("\t\t\t\t\t\t\t\t\toutput.img = positions[i].firstimage2;\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t// 마커를 생성합니다\n");
      out.write("\t\t\t\t\t\t\t\t\tvar marker = new kakao.maps.Marker({\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmap : map, // 마커를 표시할 지도\n");
      out.write("\t\t\t\t\t\t\t\t\t\tposition : new kakao.maps.LatLng(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpositions[i].mapy,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpositions[i].mapx)\n");
      out.write("\t\t\t\t\t\t\t\t\t// 마커의 위치\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t// 마커에 표시할 인포윈도우를 생성합니다 \n");
      out.write("\t\t\t\t\t\t\t\t\tvar infowindow = new kakao.maps.InfoWindow({\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcontent : \"<b>\" + positions[i].title\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"</b><br>\" + positions[i].addr1,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tremovable : true\n");
      out.write("\t\t\t\t\t\t\t\t\t// 인포윈도우에 표시할 내용\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t// 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다\n");
      out.write("\t\t\t\t\t\t\t\t\t// 이벤트 리스너로는 클로저를 만들어 등록합니다 \n");
      out.write("\t\t\t\t\t\t\t\t\t// for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다\n");
      out.write("\t\t\t\t\t\t\t\t\tkakao.maps.event.addListener(marker, 'click',\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmakeOverListener(map, marker,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tinfowindow, output));\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</script>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!-- Google Maps & Contact Info Area End -->\n");
      out.write("\n");
      out.write("\t<!-- ui middle aligned center aligned grid -->\n");
      out.write("\t<div class=\"roberto-rooms-area section-padding-100-0\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<table class=\"ui celled table\">\n");
      out.write("\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>축제명</td>\n");
      out.write("\t\t\t\t\t\t\t<td><p id=\"title\"></p></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t<tbody id=\"list\">\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>기간</td>\n");
      out.write("\t\t\t\t\t\t\t<td><p id=\"date\"></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>위치</td>\n");
      out.write("\t\t\t\t\t\t\t<td><p id=\"addr\"></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>전화번호</td>\n");
      out.write("\t\t\t\t\t\t\t<td><p id=\"tel\"></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t<td><p id=\"img\"></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div>\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Footer Area Start -->\n");
      out.write("\t<footer class=\"footer-area section-padding-80-0\">\n");
      out.write("\t\t<!-- Main Footer Area -->\n");
      out.write("\t\t<div class=\"main-footer-area\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row align-items-baseline justify-content-between\">\n");
      out.write("\t\t\t\t\t<!-- Single Footer Widget Area -->\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-6 col-lg-3\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget mb-80\">\n");
      out.write("\t\t\t\t\t\t\t<!-- Footer Logo -->\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"footer-logo\"><img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/ezenlogo2.png\" alt=\"\"></a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-6 col-lg-9\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget mb-80\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<h4>+82 042-1234-1234</h4>\n");
      out.write("\t\t\t\t\t\t\t<span>ezentour@ezen.com</span> <span>대전광역시 서구 대덕대로 325\n");
      out.write("\t\t\t\t\t\t\t\t스타게이트 7층</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Copywrite Area -->\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"copywrite-content\">\n");
      out.write("\t\t\t\t<div class=\"row align-items-center\">\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-md-12\" align=\"center\">\n");
      out.write("\t\t\t\t\t\t<!-- Copywrite Text -->\n");
      out.write("\t\t\t\t\t\t<div class=\"copywrite-text\">\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("\t\t\t\t\t\t\t\tCopyright &copy;\n");
      out.write("\t\t\t\t\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\n");
      out.write("\t\t\t\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t\t\t\tAll rights reserved | This template is made with <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- Footer Area End -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- **** All JS Files ***** -->\n");
      out.write("\n");
      out.write("\t<!-- jQuery 2.2.4 -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-1.11.0.min.js\"></script>\n");
      out.write("\t<!-- Popper -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/popper.min.js\"></script>\n");
      out.write("\t<!-- Bootstrap -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\n");
      out.write("\t<!-- All Plugins -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/roberto.bundle.js\"></script>\n");
      out.write("\t<!-- Active -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/default-assets/active.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/festival/../include/header.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/festival/../include/header.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/festival/../include/header.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/festival/../include/menu.jsp(42,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("username");
      // /WEB-INF/views/festival/../include/menu.jsp(42,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/festival/../include/menu.jsp(42,5) '${m_name}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${m_name}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/festival/../include/menu.jsp(63,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_field == 'U'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<!-- 일반 사용자 메뉴바 -->\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">마이페이지</a>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/user/user_reservation\">- 예약 내역</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/user/mycart?page=1\">- 장바구니</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul></li>\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/festival/../include/menu.jsp(72,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_field == 'A'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">마이페이지</a>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/admin/user_list\">- 사용자 목록</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">- 숙박업체 목록</a>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/admin/hotel_list_N\">- 승인 대기</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/admin/hotel_list_Y\">- 승인 목록</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/admin/grossprofit\">- 매출액 관리</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul></li>\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/festival/../include/menu.jsp(85,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_field == 'H'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<!-- 숙박업체 메뉴바 -->\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">마이페이지</a>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/company/hotel_list.do\">- 숙소 목록 및 등록</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/mypage/company/reservation\">- 예약 내역</a></li>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul></li>\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/festival/../include/menu.jsp(97,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty username}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.do\"style=\"background-color: #1cc3b2; color:white; font-weight:bold\">&nbsp;&nbsp;로그인&nbsp;&nbsp;</a>&nbsp;&nbsp;\n");
          out.write("\t                          \t     \t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/signUp.do\"style=\"background-color: #1cc3b2; color:white; font-weight:bold\">&nbsp;&nbsp;회원가입&nbsp;&nbsp;</a>\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"font-size: 0.9em;\" id=\"m_id\"><b>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b>님\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t환영합니다.</span>&nbsp;&nbsp;\n");
          out.write("\t                                \t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\" style=\"background-color: #1cc3b2; color:white; font-weight:bold\">&nbsp;&nbsp;로그아웃&nbsp;&nbsp;</a>\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
